/**
 * The operating mode of the list.
 *
 * Following values are allowed:
 * - `list` - The view should show the list of items and nothing else;
 * - `view` - The view should show the details of the current item;
 * - `edit` - The view should show the details of the current item and allow
 *   editing;
 * - `delete` - The view should show confirmation dialog for deleting the
 *   current item;
 * - `create` - The view should show the form for creating a new item.
 */
export type ListMode = "list" | "view" | "edit" | "delete" | "create";


/**
 * The error object returned by the API.
 */
export interface AccessPointError {
    /**
     * The HTTP status code.
     *
     * If the error did not come from the API, this value is 0.
     */
    status: number;

    /**
     * A human-readable message.
     *
     * This is the message generated by the API or by other code.
     * In most cases it will be the message that results when the
     * code and the parameters are fed to the translation function with
     * current language set to English.
     */
    message: string;

    /**
     * The unique code identifying this error.
     *
     * The code can be used to re-generate the message.
     */
    code?: string;

    /**
     * The name of the field that caused the error, if any.
     */
    field?: string;

    /**
     * Additional parameters for the message.
     *
     * These should be fed to the translation function along with the
     * code.
     */
    params?: Record<string, any>;
}


/**
 * The function used to reload the list.
 */
export type RefreshList<T> = () => Promise<AccessPointError | T[]>;


/**
 * The result returned by the `useFetchList` hook.
 */
export interface FetchListResult<T> {
    /**
     * The list of items returned by the API or `undefined` if the list
     * has not been fetched yet.
     */
    result?: T[];

    /**
     * Whether the list is currently being fetched.
     */
    loading: boolean;

    /**
     * The error returned by the API or `undefined` if there was no error.
     */
    error?: AccessPointError;

    /**
     * Reload the list of items.
     */
    trigger: RefreshList<T>;

    /**
     * Clear any errors and results.
     */
    reset: () => void;
}
