/**
 * The methods accepted by the API.
 */
export type AccessPointMethod = "GET" | "POST" | "PUT" | "DELETE";


/**
 * The error object returned by the API.
 */
export interface AccessPointError {
    /**
     * The HTTP status code.
     *
     * If the error did not come from the API, this value is 0.
     */
    status: number;

    /**
     * A human-readable message.
     *
     * This is the message generated by the API or by other code.
     * In most cases it will be the message that results when the
     * code and the parameters are fed to the translation function with
     * current language set to English.
     */
    message: string;

    /**
     * The unique code identifying this error.
     *
     * The code can be used to re-generate the message.
     */
    code?: string;

    /**
     * The name of the field that caused the error, if any.
     */
    field?: string;

    /**
     * Additional parameters for the message.
     *
     * These should be fed to the translation function along with the
     * code.
     */
    params?: Record<string, any>;
}
